# Generated by Django 4.0.2 on 2022-02-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0002_rename_activegoods_activegoodsmodel_and_more'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='GoodsModel',
        ),
    ]
