# Generated by Django 4.0.2 on 2022-02-21 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('img1', models.ImageField(upload_to='actives', verbose_name='图片1')),
                ('start_time', models.CharField(max_length=30, verbose_name='开始时间')),
                ('end_time', models.CharField(max_length=30, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '活动信息',
                'verbose_name_plural': '活动信息',
                'db_table': 'app_actives',
            },
        ),
        migrations.CreateModel(
            name='ActiveGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0.88, verbose_name='折扣率')),
                ('active', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='actives.active', verbose_name='活动名')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actives', to='goods.goods', verbose_name='商品名')),
            ],
            options={
                'verbose_name': '活动详情',
                'verbose_name_plural': '活动详情',
                'db_table': 'app_active_goods',
            },
        ),
    ]
