# Generated by Django 4.0.2 on 2022-02-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('actives', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveGoods',
            new_name='ActiveGoodsModel',
        ),
        migrations.RenameModel(
            old_name='Active',
            new_name='ActiveModel',
        ),
    ]
